import {Hand,Utensils,Circle,Sparkles,Mouse,Square,Sun,Moon,RefreshCw,Check,Leaf,Flower2,Snowflake,Trash2,Move} from 'lucide-react';
import {Panel,Toggle} from './Panel.jsx';
export const CAT_TOOLS=[{id:'food',name:'食物',hint:'一起吃点小点心',Icon:Utensils},{id:'yarn',name:'毛线球',hint:'轻轻拍，再追两步',Icon:Circle},{id:'scratch',name:'猫抓板',hint:'伸展一下小爪子',Icon:Square},{id:'wand',name:'逗猫棒',hint:'轻移鼠标逗一逗',Icon:Sparkles},{id:'mouse',name:'玩具小鼠',hint:'伏低、观察、轻扑',Icon:Mouse},{id:'pet',name:'轻抚',hint:'一会儿温柔的陪伴',Icon:Hand}];
export const CAT_TIME_NAMES={day:'白天',night:'黑夜'};
export function CatToolsPanel({selected,onSelect,onClose}){return <Panel title="带一点小玩意，来陪猫咪" subtitle="先选道具，再点一只猫或石板地面。按 Esc 收起道具。" onClose={onClose}><div className="cat-tools-grid">{CAT_TOOLS.map(({id,name,hint,Icon})=><button key={id} aria-pressed={selected===id} className={selected===id?'selected':''} onClick={()=>onSelect(id)}><Icon/><strong>{name}</strong><small>{hint}</small></button>)}</div><p className="inline-note">食盆可以招待两只猫。猫抓板最多放三块，在「庭院」中移动或收起。</p></Panel>}
const seasons=[['spring','春日','樱花随风落',Flower2],['summer','夏日','绿荫绣球开',Sun],['autumn','秋日','金叶铺庭边',Leaf],['winter','冬日','枝头落薄雪',Snowflake]];
export function CatSeasonPanel({environment,onChange,onClose}){return <Panel title="四时庭院，猫在身边" subtitle="让光线与落叶，陪着日子慢慢变化。" onClose={onClose}><button className={`auto-choice ${environment?.season==='auto'?'selected':''}`} onClick={()=>onChange({season:'auto'})}><span><RefreshCw size={17}/>跟随日期 · 北半球四季</span>{environment?.season==='auto'&&<Check size={17}/>}</button><div className="season-grid">{seasons.map(([id,name,desc,Icon])=><button className={`season-card ${id} ${environment?.season===id?'selected':''}`} key={id} aria-pressed={environment?.season===id} onClick={()=>onChange({season:id})}><span className="season-symbol"><Icon/><b>{name[0]}</b></span><strong>{desc}</strong><small>{name}的庭院气息</small></button>)}</div><p className="inline-note">春花、夏荫、秋叶、冬雪。四时更替，小院和猫咪熟悉的位置一直都在。</p></Panel>}
export function CatTimePanel({environment,onChange,onClose}){return <Panel title="一院晴光，一院月色" subtitle="白天晒太阳，黑夜看流萤。" onClose={onClose}><div className="day-choices cat-time-choices">{[['auto','跟随本机时间','07:00—19:00 白天，其余时间为黑夜',RefreshCw],['day','白天 · 一院晴光','暖暖的石板，适合晒太阳',Sun],['night','黑夜 · 月下小院','温柔月光铺下来，花间几只流萤',Moon]].map(([id,name,desc,Icon])=><button key={id} aria-pressed={environment?.time===id} className={environment?.time===id?'selected':''} onClick={()=>onChange({time:id})}><Icon/><span><strong>{name}</strong><small>{desc}</small></span>{environment?.time===id&&<Check size={17}/>}</button>)}</div></Panel>}
export function CatGardenPanel({view,onChange,onRemoveProp,onMoveProp,onFacility,onClose}){const env=view?.environment||{},boards=(view?.props||[]).filter(p=>p.persistent);return <Panel title="小院里的日常" subtitle="一处小天地，慢慢住成喜欢的样子。" onClose={onClose}><Toggle label="花叶与四时效果" description="少量花瓣、落叶与庭边薄雪" checked={env.particles!==false} onChange={particles=>onChange({particles})}/><Toggle label="夜间萤火虫" description="春夏花间，秋夜少许；冬天歇一歇" checked={env.fireflies!==false} onChange={fireflies=>onChange({fireflies})}/><div className="section-divider"/><div className="day-choices"><button onClick={()=>onFacility('bed')}><Moon/><span><strong>去草垫上做个梦</strong><small>慢慢走上石阶，在草垫里蜷起来</small></span></button><button onClick={()=>onFacility('rock')}><Sun/><span><strong>暖石上晒太阳</strong><small>绕过花丛，找个舒服的位置趴一会儿</small></span></button><button onClick={()=>onFacility('step')}><Square/><span><strong>石阶上看看庭院</strong><small>沿石板路走近台阶，听一会儿风</small></span></button><button onClick={()=>onFacility('climbing')}><Sparkles/><span><strong>跳上猫爬架</strong><small>轻轻跃上低平台，一次招待一只猫</small></span></button><button onClick={()=>onFacility('water')}><Utensils/><span><strong>去水碗边看看</strong><small>沿石阶慢慢走近原画里的水碗</small></span></button></div><div className="cat-facility-list"><p className="inline-note">庭院猫抓板 · {boards.length} / 3</p>{boards.map((p,i)=><div key={p.id}><span>猫抓板 {i+1}</span><span><button className="icon-button" aria-label={`移动猫抓板 ${i+1}`} onClick={()=>onMoveProp(p.id)}><Move size={16}/></button><button className="icon-button" aria-label={`收起猫抓板 ${i+1}`} onClick={()=>onRemoveProp(p.id)}><Trash2 size={16}/></button></span></div>)}</div><p className="inline-note">也可以直接轻点画面中的草垫、石阶、暖石、水碗或爬架。轻抚休息中的猫，就能温柔唤醒它。</p></Panel>}
