import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Fish,Leaf,Cloud,Moon,Sun,Monitor,Settings,Maximize,Minimize,Check,RefreshCw,Minus,EyeOff,X,Hand,Shell,BookOpen,Waves,ChevronDown,Cat,PawPrint,Sparkles,Flower2} from 'lucide-react';
import CatScene from './components/CatScene.jsx';
import CatStudio from './components/CatStudio.jsx';
import CatManager from './components/CatManager.jsx';
import {CatToolsPanel,CatSeasonPanel,CatTimePanel,CatGardenPanel,CAT_TOOLS,CAT_TIME_NAMES} from './components/CatPanels.jsx';
import {resolveEnvironment} from './themes/cats/environment.js';
import Pond from './components/Pond.jsx';
import CoastScene from './components/CoastScene.jsx';
import BottlePanel,{BottleIcon} from './components/BottlePanel.jsx';
import {ThemePanel,BucketPanel,GuidePanel,TidePanel,TongsIcon,TideIcon,PHASE_NAMES,tideTime,tideCountdownLabel} from './components/CoastPanels.jsx';
import {loadTheme,saveTheme,THEMES} from './themes/registry.js';
import {Panel} from './components/Panel.jsx';
import WeatherPanel,{WEATHER} from './components/WeatherPanel.jsx';
import SeasonPanel,{SEASONS} from './components/SeasonPanel.jsx';
import SettingsPanel from './components/SettingsPanel.jsx';
import KoiStudio from './components/KoiStudio.jsx';
import {loadSettings,loadFish,writeStore} from './lib/storage.js';
import {useEnvironment} from './hooks/useEnvironment.js';
import {useAmbient} from './hooks/useAmbient.js';
function FeedIcon(){return <svg width="25" height="25" viewBox="0 0 28 28" fill="none" stroke="currentColor" strokeWidth="1.4"><circle cx="14" cy="6.5" r="4"/><circle cx="7" cy="20" r="4"/><circle cx="22" cy="20" r="4"/></svg>}
export default function App(){
 const [settings,setSettings]=useState(()=>{const s=loadSettings();try {if(!localStorage.getItem('fusheng-settings'))s.reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;} catch {}return s}),[fish,setFish]=useState(loadFish),[panel,setPanel]=useState(null),[immersive,setImmersive]=useState(false),[paused,setPaused]=useState(false),[toast,setToast]=useState(''),[desktop,setDesktop]=useState(null),[windowBusy,setWindowBusy]=useState(false);const pond=useRef(null),timer=useRef(null);
 const [theme,setTheme]=useState(loadTheme),[coastView,setCoastView]=useState(null),[coastMode,setCoastMode]=useState('observe');
 const [bottleLetter,setBottleLetter]=useState(null);
 const openBottle=useCallback(letter=>{setBottleLetter(letter.id);setPanel('bottles')},[]);
 const isCoast=theme==='coast',isCats=theme==='cats';
 const [catView,setCatView]=useState(null),[catTool,setCatTool]=useState(null),[editingCat,setEditingCat]=useState(null),[movingProp,setMovingProp]=useState(null);
 const catEnv=catView?.resolved||resolveEnvironment();
 const clearCatTool=useCallback(()=>{setCatTool(null);setMovingProp(null);pond.current?.clear?.()},[]);
 const movedCatProp=useCallback(()=>setMovingProp(null),[]);
 const [pageVisible,setPageVisible]=useState(()=>!document.hidden);
 const [power,setPower]=useState({onBattery:false,suspended:false});
 useEffect(()=>{const changed=()=>setPageVisible(!document.hidden);document.addEventListener('visibilitychange',changed);return()=>document.removeEventListener('visibilitychange',changed)},[]);
 useEffect(()=>{const bridge=window.pondDesktop;if(!bridge?.onPower)return;let active=true;const receive=p=>{if(active)setPower(p)};const off=bridge.onPower(receive);bridge.getState?.().then(s=>{if(active&&s)setPower({onBattery:!!s.onBattery,suspended:!!s.suspended})});return()=>{active=false;off()}},[]);
 const effectiveLowPower=settings.lowPower||(settings.autoLowPower&&power.onBattery);
 const effectivePaused=paused||power.suspended;
 const env=useEnvironment(settings);const ambient=useAmbient(settings.sound&&!effectivePaused&&pageVisible&&!isCats,settings.volume,env.weather,env.season,env.night,theme);
 const notify=useCallback(text=>{setToast(text);clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),3300)},[]);
 function selectTheme(id){if(id===theme){setPanel(null);return}if(!saveTheme(id))notify('主题暂未保存，下次启动将使用之前的风景。');setPanel(null);setPaused(false);setCoastMode('observe');setCoastView(null);setCatTool(null);setMovingProp(null);setCatView(null);setEditingCat(null);setTheme(id)}
 const update=useCallback((key,value)=>{
  if(isCats&&(key==='sound'||key==='volume')){
   const enabled=key==='sound'?Boolean(value):settings.sound;
   let volume=key==='volume'?Math.max(0,Math.min(.6,Number(value)||0)):(settings.volume??.18);
   if(key==='sound'&&enabled&&volume===0)volume=.18;
   // Unlock/configure in the original click event, before React's effect runs.
   if(key==='sound')Promise.resolve(pond.current?.setSound?.(enabled,volume)).catch(()=>notify('庭院声音暂时没有开启，请轻点声音按钮重试。'));
   setSettings(s=>({...s,sound:enabled,volume}));return;
  }
  setSettings(s=>({...s,[key]:value}));
 },[isCats,settings.sound,settings.volume,notify]);const closePanel=useCallback(()=>setPanel(null),[]);
 const previewCatSound=useCallback(kind=>{
  if(!settings.sound||settings.volume<=0){notify('先开启庭院声音，并调高一点音量。');return;}
  Promise.resolve(pond.current?.previewSound?.(kind)).then(ok=>{if(ok===false)notify('这段声音暂未准备好，请稍后再试。')}).catch(()=>notify('声音暂未准备好，请重新开启庭院声音。'));
 },[settings.sound,settings.volume,notify]);
 useEffect(()=>{if(!writeStore('fusheng-settings',settings))notify('存储空间不足，当前设置仅保留到本次关闭。')},[settings,notify]);
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 useEffect(()=>{const bridge=window.pondDesktop;if(!bridge)return;let lastMode=false,active=true;const receive=state=>{if(!active)return;setDesktop(state);if(state.desktopMode!==lastMode){lastMode=state.desktopMode;if(state.desktopMode)setPanel(null);setImmersive(state.desktopMode)}};bridge.getState().then(receive);const off=bridge.onState(receive);return()=>{active=false;off()}},[]);
 useEffect(()=>{function onKey(e){if(e.key!=='Escape'&&e.target.closest('input,textarea,select,button,a,[role="button"],[contenteditable="true"]'))return;if(e.key==='Escape'){if(panel)setPanel(null);else if(isCats&&(catTool||movingProp))clearCatTool();else if(immersive)setImmersive(false)}if(e.code==='Space'&&!panel){e.preventDefault();pond.current?.feed();if(!isCoast&&!isCats)notify('一把鱼食，一池欢喜')}if(e.key.toLowerCase()==='h'&&!panel)setImmersive(v=>!v)}window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[panel,immersive,notify,isCoast,isCats,catTool,movingProp,clearCatTool]);
 const options=useMemo(()=>({season:env.season,weather:env.weather,night:env.night,paused:effectivePaused,desktopMode:!!desktop?.desktopMode,reducedMotion:settings.reducedMotion||effectiveLowPower,lowPower:effectiveLowPower,fishCount:settings.fishCount,fishSize:settings.fishSize,turtleCount:settings.turtleCount,quality:settings.quality,solarTerm:env.solarTerm,sound:settings.sound,volume:settings.volume,onThunder:ambient.thunder}),[env.season,env.weather,env.night,effectivePaused,settings.reducedMotion,effectiveLowPower,settings.fishCount,settings.fishSize,settings.turtleCount,settings.quality,env.solarTerm,settings.sound,settings.volume,desktop?.desktopMode,ambient.thunder]);
 function saveFish(f){const next=[...fish,f];if(!writeStore('fusheng-fish',next)){notify('存储空间不足，未能保存这尾锦鲤。');return}setFish(next);setPanel(null);notify(`${f.name}已游入池塘，下次见面它还在。`)}
 function removeFish(id){const next=fish.filter(f=>f.id!==id);if(writeStore('fusheng-fish',next)){setFish(next);notify('锦鲤已从池塘移走')}}
 function resizeFish(id,size){const next=fish.map(f=>f.id===id?{...f,size}:f);if(writeStore('fusheng-fish',next))setFish(next);else notify('存储空间不足，未能保存大小。')}
 async function desktopAction(action,value){setWindowBusy(true);try{const result=await window.pondDesktop[action](value);if(result){setDesktop(result);if(action==='setDesktopMode'&&result.message)notify(result.message)}}catch{notify('窗口操作未完成，请从菜单栏重试。')}finally{setWindowBusy(false)}}
 const getStats=useCallback(()=>pond.current?.stats(),[]);
 const WeatherIcon=WEATHER[env.weather]?.Icon||Sun;const hidden=immersive||desktop?.desktopMode;
 return <main className={`app theme-${theme} season-${isCats?catEnv.season:env.season} ${(isCats?catEnv.night:env.night)?'night':'day'} weather-${env.weather} ${hidden?'immersive':''} ${desktop?'native-app':''}`}>
  {ambient.tracks.map(track=><audio key={track.id} data-ambient={track.id} ref={track.ref} src={track.url} loop={track.loop} preload="none" hidden aria-hidden="true"/>)}<div className="pond-background"/><div className="scene-light"/>{isCats?<CatScene key="cats" ref={pond} options={options} desktop={desktop} tool={catTool} moveProp={movingProp} editing={panel==='cat-studio'} onChange={setCatView} notify={notify} onClearTool={clearCatTool} onMoved={movedCatProp}/>:isCoast?<CoastScene key="coast" ref={pond} options={options} desktop={desktop} mode={coastMode} onChange={setCoastView} notify={notify} onBottle={openBottle}/>:<Pond key="koi" ref={pond} options={options} fish={fish} desktop={desktop}/>}<div className="edge-shade"/>
  <div className="hud"><header className="topbar"><div className="brand"><span className="brand-symbol">{isCats?<Cat size={34} strokeWidth={1.5}/>:isCoast?<Waves size={34} strokeWidth={1.5}/>:<Fish size={34} strokeWidth={1.5}/>}</span><div><h1>浮生</h1><button className="theme-trigger" aria-label="切换主题" onClick={()=>setPanel('theme')}>{THEMES.find(t=>t.id===theme).name}<ChevronDown size={13}/></button></div></div>{isCats?<button className="weather-badge" aria-label="庭院光阴" onClick={()=>setPanel('day')}>{catEnv.night?<Moon size={23}/>:<Sun size={23}/>}<span>{SEASONS[catEnv.season].label}</span><strong>{CAT_TIME_NAMES[catEnv.time]}</strong></button>:isCoast?<div className="weather-badge coast-weather-badge" aria-label="海边天气"><WeatherIcon size={23}/><span>{env.city.name}</span><strong>{env.data?`${Math.round(env.data.temperature)}°`:'—°'}</strong><span className="weather-label">{settings.weather==='auto'?(env.status==='live'?env.data.description:env.status==='loading'?'获取中':env.status==='cached'?'缓存':'离线'):WEATHER[env.weather].name}</span></div>:<button className="weather-badge" onClick={()=>setPanel('weather')} aria-label="打开天气设置"><WeatherIcon size={23}/><span>{env.city.name}</span><strong>{env.data?`${Math.round(env.data.temperature)}°`:'—°'}</strong><span className="weather-label">{settings.weather==='auto'?(env.status==='live'?env.data.description:env.status==='loading'?'获取中':env.status==='cached'?'缓存':'离线'):WEATHER[env.weather].name}</span></button>}</header>
  <div className="poem"><span className="poem-line"/><p>{isCats?'猫在庭间':isCoast?'潮来潮往':'一池清欢'}</p><span className="poem-line"/><small>{isCats?'一院晴光，几只小小陪伴。':isCoast?'等一阵潮，拾一点欢喜。':'把日子，慢慢游成诗。'}</small></div>
  <div className="scene-status"><p>{isCats?'有猫的日子，慢一点也好':isCoast?'一湾浅海，半日清闲':<>{SEASONS[env.season].label}<i/> {env.night?'夜色':'白昼'} <span className="solar-term">· {env.solarTerm}</span></>}</p><span>{isCats?`庭院 ${catView?.visibleCount??catView?.activeCount??0} / 12 只 · 安睡 ${catView?.sleepingCount||0} 只`:isCoast?`贝壳 ${coastView?.shells||0} 枚 · 小桶 ${coastView?.bucket?.length||0}/12`:<>{fish.length+settings.fishCount} 尾锦鲤 {settings.turtleCount>0&&`· ${settings.turtleCount} 只小乌龟`}</>} {paused&&'· 静止片刻'}</span></div>
  {isCoast&&<button className="tide-badge" aria-label="潮汐信息" onClick={()=>setPanel('tide')}><TideIcon size={19}/><span><strong>{PHASE_NAMES[coastView?.tide?.phase]||'涨潮中'}</strong><small>{tideCountdownLabel(coastView?.tide)} {tideTime(coastView?.tide?.remainingSeconds)}</small></span><meter min="0" max="1" value={coastView?.tide?.level||0} aria-label="潮位"/></button>}
  <div className="dock-wrap"><p className="feed-hint"><span/>{isCats?(catTool?`${CAT_TOOLS.find(t=>t.id===catTool)?.name} · 轻点猫咪或石板地面`:movingProp?'轻点空石板，挪动猫抓板':'带一点小玩意，来陪猫咪慢慢过日子'):isCoast?(coastMode==='catch'?'钳子拾贝、抓鱼；游鱼会躲闪，搁浅一捡即得':'长按沙滩，画下心情；轻点小瓶，拾起一封来信'):'轻点水面，投下一份小小欢喜'}<span/></p><nav className="dock" aria-label={isCats?'庭院工具栏':isCoast?'赶海工具栏':'池塘工具栏'}>
{isCats?<><button className={panel==='cats'||panel==='cat-studio'?'active':''} onClick={()=>setPanel('cats')}><Cat/><span>猫咪</span></button><button className={catTool||panel==='cat-tools'?'active':''} aria-pressed={!!catTool} onClick={()=>setPanel('cat-tools')}><PawPrint/><span>道具</span></button><button className={panel==='season'?'active':''} onClick={()=>setPanel('season')}><Leaf/><span>四时</span></button><button className={panel==='day'?'active':''} onClick={()=>setPanel('day')}>{catEnv.night?<Moon/>:<Sun/>}<span>光阴</span></button><button className={panel==='garden'?'active':''} onClick={()=>setPanel('garden')}><Flower2/><span>庭院</span></button><button className={panel==='settings'?'active':''} onClick={()=>setPanel('settings')}><Settings/><span>设置</span></button></>:<>    {isCoast?<><button className={coastMode==='catch'?'active':''} aria-label={coastMode==='catch'?'捕捉模式，点击切回观察':'观察模式，点击切换捕捉'} aria-pressed={coastMode==='catch'} onClick={()=>{setCoastMode(v=>v==='catch'?'observe':'catch');setPanel(null)}}>{coastMode==='catch'?<TongsIcon/>:<Hand/>}<span>{coastMode==='catch'?'捕捉':'观察'}</span></button><button className={panel==='bucket'?'active':''} onClick={()=>setPanel('bucket')}><Shell/><span>小桶{coastView?.bucket?.length>0&&<b className="dock-count">{coastView.bucket.length}</b>}</span></button><button className={panel==='guide'?'active':''} onClick={()=>setPanel('guide')}><BookOpen/><span>图鉴</span></button></>:<><button onClick={()=>{pond.current?.feed();notify('一把鱼食，一池欢喜')}}><FeedIcon/><span>投食</span></button><button className={panel==='season'?'active':''} onClick={()=>setPanel(panel==='season'?null:'season')}><Leaf/><span>四时</span></button></>}
    {isCoast?<><button className={`tide-tool ${panel==='tide'?'active':''}`} aria-label="潮汐" onClick={()=>setPanel(panel==='tide'?null:'tide')}><TideIcon/><span>潮汐</span></button><button className={panel==='bottles'?'active':''} aria-label="漂流瓶" onClick={()=>{setBottleLetter(null);setPanel(panel==='bottles'?null:'bottles')}}><BottleIcon/><span>漂流瓶</span></button></>:<><button className={panel==='weather'?'active':''} onClick={()=>setPanel(panel==='weather'?null:'weather')}><Cloud/><span>天气</span></button><button className={panel==='day'?'active':''} onClick={()=>setPanel(panel==='day'?null:'day')}>{env.night?<Sun/>:<Moon/>}<span>日夜</span></button></>}{!isCoast&&<button className={panel==='studio'?'active':''} onClick={()=>setPanel('studio')}><Fish/><span>画锦鲤</span></button>}<button className={panel==='settings'?'active':''} onClick={()=>setPanel(panel==='settings'?null:'settings')}><Settings/><span>设置</span></button></>}</nav></div>
  <div className="scene-actions"><button className="desktop-button" disabled={windowBusy} aria-label="桌面模式" title={desktop?.desktopSupported?'进入桌面模式 · ⌘ ⇧ K 恢复控制':'桌面模式'} onClick={()=>desktop?.desktopSupported?desktopAction('setDesktopMode',true):setPanel('desktop')}><Monitor/><span>桌面</span></button><button className="immersive-button" onClick={()=>{setImmersive(true);notify('已收起界面 · 按 Esc 或右下角按钮返回')}}><Maximize size={18}/><span>沉浸</span></button></div></div>
  {isCats&&(catTool||movingProp)&&!panel&&!hidden&&<div className="cat-tool-pill"><PawPrint size={15}/>{movingProp?'正在移动猫抓板':`已选 ${CAT_TOOLS.find(t=>t.id===catTool)?.name}`}<button aria-label="收起庭院道具" onClick={clearCatTool}><X size={15}/></button></div>}
  {desktop&&!desktop.desktopMode&&<div className="window-bar"><div className="window-drag" title="拖动这里移动窗口；拖动窗口边缘调整大小"/><div className="window-actions" role="group" aria-label="窗口控制"><button disabled={windowBusy} aria-label={desktop.fullScreen?'退出全屏':'窗口全屏'} title={desktop.fullScreen?'退出全屏':'全屏'} onClick={()=>desktopAction('setFullScreen',!desktop.fullScreen)}>{desktop.fullScreen?<Minimize size={15}/>:<Maximize size={15}/>}</button><button aria-label="最小化窗口" title="最小化" onClick={()=>desktopAction('minimize')}><Minus size={16}/></button><button aria-label="隐藏窗口" title="隐藏 · 菜单栏锦鲤图标或 ⌘ ⇧ K 恢复" onClick={()=>desktopAction('hide')}><EyeOff size={16}/></button><button className="window-close" aria-label="关闭程序" title="关闭程序" onClick={()=>desktopAction('quit')}><X size={17}/></button></div></div>}
  {hidden&&!desktop?.desktopMode&&<button className="restore-button" aria-label="退出沉浸模式" onClick={()=>setImmersive(false)}><Minimize size={19}/></button>}
  {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
  {panel==='theme'&&<ThemePanel theme={theme} onSelect={selectTheme} onClose={closePanel}/>}
  {isCoast&&panel==='bucket'&&<BucketPanel view={coastView} onRelease={v=>pond.current?.release(v)} onClose={closePanel}/>}
  {isCoast&&panel==='guide'&&<GuidePanel view={coastView} onClose={closePanel}/>}
  {isCoast&&panel==='tide'&&<TidePanel view={coastView} onDirection={direction=>{setPaused(false);pond.current?.tideDirection(direction)}} onDebug={(a,v)=>pond.current?.debug?.(a,v)} onClose={closePanel}/>}
  {isCoast&&panel==='bottles'&&<BottlePanel view={coastView?.bottles} selectedId={bottleLetter} onDraft={value=>pond.current?.bottles?.draft(value)} onSend={value=>{const result=pond.current?.bottles?.send(value);if(result?.ok)setPanel(null);return result}} onClose={closePanel}/>}
  {panel==='weather'&&<WeatherPanel env={env} mode={settings.weather} onChange={v=>update('weather',v)} onClose={closePanel} notify={notify}/>}
  {panel==='desktop'&&<Panel title="让风景，住进桌面" subtitle="轻轻流动，陪你做自己的事。" onClose={closePanel}><div className="desktop-notice"><Monitor size={25}/><div><strong>{desktop?'当前系统暂不支持桌面风景':'请打开「浮生锦鲤池」桌面应用'}</strong><p>{desktop?'可以先在这里收起界面，安静看风景。':'在桌面应用首页点「桌面」，当前风景就会铺在桌面图标下方，鼠标操作照常。浏览器内可以先体验沉浸模式。'}</p></div></div><p className="shortcut-note">桌面应用中按 ⌘ ⇧ K，或点菜单栏锦鲤图标，可随时恢复控制。</p><button className="primary-button" onClick={()=>{setPanel(null);setImmersive(true)}}><Maximize size={18}/>先体验沉浸模式</button></Panel>}
  {panel==='season'&&!isCats&&<SeasonPanel mode={settings.season} current={env.season} solarTerm={env.solarTerm} onChange={v=>update('season',v)} onClose={closePanel}/>}
  {panel==='day'&&!isCats&&<Panel title="日升月落，各有温柔" subtitle={isCoast?'晨光落在潮线，夜色映入浅海。':'白日有蝶，入夜有萤。'} onClose={closePanel}><div className="day-choices">{[{id:'auto',name:'跟随日夜',desc:'依据城市天气与本机时间',Icon:RefreshCw},{id:'day',name:'留住白昼',desc:isCoast?'晨光轻落，海浪细语':'阳光轻落，蝴蝶翩跹',Icon:Sun},{id:'night',name:isCoast?'一海星光':'一池星光',desc:isCoast?'月色随潮，晚风徐徐':'晚风徐徐，流萤点点',Icon:Moon}].map(({id,name,desc,Icon})=><button className={settings.day===id?'selected':''} key={id} onClick={()=>update('day',id)}><Icon size={25}/><span><strong>{name}</strong><small>{desc}</small></span>{settings.day===id&&<Check size={18}/>}</button>)}</div></Panel>}
  {panel==='studio'&&<KoiStudio onClose={closePanel} onSave={saveFish} fish={fish} onRemove={removeFish} onResize={resizeFish} turtleCount={settings.turtleCount} onTurtles={v=>update('turtleCount',v)}/>}
  {isCats&&panel==='cats'&&<CatManager view={catView} onAdd={()=>{clearCatTool();setEditingCat(null);setPanel('cat-studio')}} onEdit={cat=>{clearCatTool();setEditingCat(cat);setPanel('cat-studio')}} onToggle={(id,awake)=>{const result=pond.current?.setActive(id,awake);if(result?.ok)setPanel(null)}} onArchive={id=>pond.current?.archiveCat(id)} onRemove={id=>pond.current?.removeCat(id)} onImport={design=>pond.current?.saveDesign(null,design)} onClose={closePanel} notify={notify}/>}
  {isCats&&panel==='cat-studio'&&<CatStudio cat={editingCat} onSave={design=>{const result=pond.current?.saveDesign(editingCat?.id,design);if(result?.ok){notify(editingCat?'新毛色已经保存。':result.message||'新朋友来庭院了。');setPanel('cats')}else notify(result?.message||'暂时没有保存，请稍后重试。');return result}} onClose={()=>setPanel('cats')} notify={notify}/>}
  {isCats&&panel==='cat-tools'&&<CatToolsPanel selected={catTool} onSelect={id=>{if(catTool===id)clearCatTool();else{setMovingProp(null);setCatTool(id)}setPanel(null)}} onClose={closePanel}/>}
  {isCats&&panel==='season'&&<CatSeasonPanel environment={catView?.environment} onChange={v=>pond.current?.setEnvironment(v)} onClose={closePanel}/>}
  {isCats&&panel==='day'&&<CatTimePanel environment={catView?.environment} onChange={v=>pond.current?.setEnvironment(v)} onClose={closePanel}/>}
  {isCats&&panel==='garden'&&<CatGardenPanel view={catView} onChange={v=>pond.current?.setEnvironment(v)} onRemoveProp={id=>pond.current?.removeProp(id)} onMoveProp={id=>{setCatTool(null);setMovingProp(id);setPanel(null)}} onFacility={id=>{const result=pond.current?.visitFacility(id);if(result?.ok)setPanel(null)}} onClose={closePanel}/>}
  {panel==='settings'&&<SettingsPanel theme={theme} onSeason={()=>setPanel('season')} soundStatus={isCats?(catView?.audioStatus||'off'):ambient.status} soundDescription={isCats?'轻柔微风常伴，偶尔几声猫叫与鸟鸣':ambient.description} onPreviewSound={isCats?previewCatSound:undefined} getStats={getStats} settings={settings} update={update} paused={paused} setPaused={setPaused} desktop={desktop} power={{onBattery:power.onBattery,suspended:power.suspended,lowPower:effectiveLowPower}} onDesktop={v=>desktopAction('setDesktopMode',v)} onGlobal={v=>desktopAction('setGlobalInteraction',v)} onLogin={v=>desktopAction('setLaunchAtLogin',v)} onClose={closePanel} notify={notify}/>}
 </main>
}
